/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jwuwbkonbqspqtpmghdl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3dXdia29uYnFzcHF0cG1naGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NzUxNTYsImV4cCI6MjA3OTI1MTE1Nn0.9btPDOcSdvekvG-0s8xgAadib-K1tqcg7tHfCqIP7wI"